stages:
- stage: JobDeploy
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '211022 - DevOps Conf 2021 @DotNetCode/JobsOnDevOps/AmazingJob/AmazingJob.csproj'
        arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/WebJob/App_Data/jobs/triggered/AmazingJob'
        zipAfterPublish: false
        modifyOutputPath: false
    - script: 'echo "dotnet AmazingJob.dll" > run.cmd'
      workingDirectory: '$(Build.ArtifactStagingDirectory)/WebJob/App_Data/jobs/triggered/AmazingJob'
      displayName: 'Create run.cmd'
    - task: FtpUpload@2
      displayName: 'FTP Upload: $(Build.ArtifactStagingDirectory)/WebJob'
      inputs:
        serverEndpoint: DOC21Ftp
        rootDirectory: '$(Build.ArtifactStagingDirectory)/WebJob'
        remoteDirectory: /site/wwwroot
        preservePaths: true
        trustSSL: true
